### ISSUE TITLE
Uncaught TypeError - WEBPACK_IMPORTED_MODULE_5

### ISSUE THREAD

**Issue by web-surfer** [bendrucker/creditcards#27]
NOTE: My app uses Webpack 4

When using the `card` `expiration` and `cvc` functions to validate, I get the following error (below is an example of the error I get when trying to validate `cvc`):

`Uncaught TypeError: creditcards_cvc__WEBPACK_IMPORTED_MODULE_5___default.a.isValid is not a function`

This only happens when using versions `3.0.0` and up of `creditcards` (version `2.1.2` works fine and doesn't produce this error).

**Comment by bendrucker** [comment]
Hi, closing because there's nothing too special about this module. Happy to continue the discussion but I consider this more of a general support question and I only keep actual bugs open.

You should probably explore the module and see what it is (i.e. what does `require('creditcards')` return. A `TypeError` isn't very helpful as it only tells us one thing that's missing and not what's there. If that doesn't turn up anything useful, I'd consider looking at a full repro project that triggers this error given a `npm install && npm test`.
