### ISSUE TITLE
Support eager type matching

### ISSUE THREAD

**Issue by bendrucker** [bendrucker/creditcards#4]
Allow card to be matched against a permissive regex that just matches against the first few digits of the card number. The type would be returned for invalid cards, so `4` would match Visa immediately.

**Comment by bbean86** [comment]
@bendrucker I've solved some of this in my fork. Check out this commit: https://github.com/bbean86/creditcards/commit/ded70831d9da51722a07be88bfad1625e9801273

I added `quickPattern` as an attribute on each of our card type objects, which is now used by the `type()` function in place of `pattern`. This means `type()` returns `visa` when given a `number` as short as `4`. In order to keep the remaining tests passing and the `isValid()` function working, I added `length` as an attribute to help determine a card number's validity. A valid number matches the quickPattern, the length, and passes luhn algorithm validation.

**Comment by bendrucker** [comment]
Yeah I looked at your implementation. The lengths really aren't necessary. You want to err on the side of permissiveness with cc validation and the research I did when I published this suggested that there are certain ultra rare cases where a Visa could be less than 16 digits, for example:

http://en.wikipedia.org/wiki/Bank_card_number

I'm definitely not going have this be a breaking change which yours is. Plan is to change the signature of `type` to `type(number, guess)` with the default behavior remaining the same.

**Comment by bbean86** [comment]
Agreed. My implementation was quick and dirty to get something shipped, but I'd love to get all corner cases covered. I realized I was cutting off those Visa numbers and decided to deal with it in the short term. 

I like leaving default behavior the same, so I'd like to hear more about your plan for `type`. I think I see where you're going, is `guess` a boolean? That would be a good way to control which pattern is used to match, especially in concert with your `cc-eager-type` attribute.

**Comment by bendrucker** [comment]
Yes, but I'm probably going to opt to not do an attribute because it's less clear than just adding the functionality as a new property. This:

https://github.com/bendrucker/angular-credit-cards/blob/master/src/number.js#L22-L24

Will become this:

```js
ngModelController.$ccType = ccNumberController.type = card.type(number);
ngModelController.$ccEagerType = ccNumberController.eagerType = card.type(number, true);
```

**Comment by bbean86** [comment]
:+1: to the property, I like the solution.

**Comment by bendrucker** [comment]
This is close to ready. Just wrote up https://github.com/bendrucker/creditcards-types to extract the type handling from this lib.

**Comment by bendrucker** [comment]
Done! Will hook up angular-credit-cards with the new property later this week
