### ISSUE TITLE
Add formatting methods

### ISSUE THREAD

**Issue by bendrucker** [bendrucker/creditcards#5]
Format cards according to a spacing standard

**Comment by bbean86** [comment]
You can see my implementation in this commit: https://github.com/bbean86/creditcards/commit/6065e10cbe0b83e373875bc8986a023b9aefaeff 

(Note: I fix the default return value for `formattedParse` in the next commit)

`formatNumber` relies on the meta `arguments` object, since `replace` sends a variable number of matches to its callback. 

Like I mentioned in https://github.com/bendrucker/angular-credit-cards/issues/18, this function relies on the `length` property of the card object. Dealing with Visas having multiple possible lengths and multiple possible formats could be interesting. My implementation assumes 16 digit Visas with xxxx xxxx xxxx xxxx formatting.

**Comment by bendrucker** [comment]
This is going to be called `format` but likely borrow some code from your implementation

**Comment by bbean86** [comment]
:+1:

**Comment by bendrucker** [comment]
Added in 95d30a8342c17b69d3b7b370ef393a0df028ec0e
